### ISSUE TITLE
Build fails on FreeBSD i386 after upgrade from 0.9.14 to 0.9.16

### ISSUE THREAD

**Issue by Jehops** [bbuchfink/diamond#189]
Hello,

Here are build logs.

0.9.16 (FreeBSD 11 i386):
http://pkg.awarnach.mathstat.dal.ca/data/11i386-default/2018-01-28_12h22m40s/logs/errors/diamond-0.9.16.log

0.9.14 (FreeBSD 11 i386):
http://pkg.awarnach.mathstat.dal.ca/data/11i386-default/2018-01-28_12h25m19s/logs/diamond-0.9.14.log

0.9.16 (FreeBSD 11 amd64):
http://pkg.awarnach.mathstat.dal.ca/data/11amd64-default/2018-01-28_11h33m39s/logs/diamond-0.9.16.log

**Comment by bbuchfink** [comment]
Hi,

I have just commited a patch that should fix this, let me know.

**Comment by Jehops** [comment]
This looks like it fixed the i386-specific problem, but introduced a new problem affecting only FreeBSD  version 10.

Build logs using the latest commit:

10i386: http://pkg.awarnach.mathstat.dal.ca/data/10i386-default/2018-01-30_05h37m03s/logs/errors/diamond-0.9.16.log

10amd64: http://pkg.awarnach.mathstat.dal.ca/data/10amd64-default/2018-01-30_05h37m03s/logs/errors/diamond-0.9.16.log

11i386: http://pkg.awarnach.mathstat.dal.ca/data/11i386-default/2018-01-30_05h37m03s/logs/diamond-0.9.16.log

11amd64: http://pkg.awarnach.mathstat.dal.ca/data/11amd64-default/2018-01-30_05h53m06s/logs/diamond-0.9.16.log

**Comment by bbuchfink** [comment]
Could you try again with the latest commit please?

**Comment by Jehops** [comment]
There is still a problem on 10 i386/amd64:
http://pkg.awarnach.mathstat.dal.ca/data/10i386-default/2018-01-30_18h15m39s/logs/errors/diamond-0.9.16.log
http://pkg.awarnach.mathstat.dal.ca/data/10amd64-default/2018-01-30_18h15m39s/logs/errors/diamond-0.9.16.log

**Comment by bbuchfink** [comment]
Ok, please try again with the latest version.

**Comment by Jehops** [comment]
Looks good.  Thank you.
