### ISSUE TITLE
DIAMOND computing requirements/error calling unlink

### ISSUE THREAD

**Issue by indren** [bbuchfink/diamond#267]
Hello,
I am a new user of diamond (version 0.9.24) and have a question and an issue related to each other.

**Question** - what are the absolute minimum requirements to run diamond (e.g. memory, CPU and storage). I understand this strongly depends on sample and db size, however, what would you recommend as min requirements for any run on diamond?

**Issue** - the reason of my question is that I have been trying to run diamond blastx with just 1 sample (~8G) using the nr database (~110G) and it keeps failing with the following error:

Initializing temporary storage... Device or resource busy
 [0.143507s]
Error: Error calling unlink.

I assume this error relates to memory issues so I have tried running blastx with -b1.0, -b0.5 and -b0.1 (I tried quite a few runs just to see what happens). I kept -c parameter at default as my server is not of high memory. Finally, the manual states that the temporary directory is set to the output directory by default which is fine as my output directory has 600Gb of free space at the moment. However, I kept getting the same error, so I tried setting -t /dev/shm but this run also failed with the following error:

Searching alignments... No space left on device
terminate called after throwing an instance of 'File_write_exception'
No space left on device
  what():  Error writing file /dev/shm/diamond-tmp-ztQN69terminate called recursively

I am worried the server I am using, which is allocated by my university (I am a PhD student) is not meeting diamond's computational requirements, hence my question. My server has 7.8G of RAM, 8G of Swp, max of 2 CPU threads. I also have a folder allocated by my IT in the Network Location with 1Tb of space which I use as the output directory. I have an option to increase RAM to 16G and also increase the VM from 2 cores to 4, but am wondering will this be enough?

Indre

**Comment by bbuchfink** [comment]
Your system should be sufficient to run Diamond with a block size parameter of 1.0. You will need lots of temporary disk space so you can't use /dev/shm as temp directory.

It seems like the unlink command does not work on your system for some reason. Please try to clone the latest version of the Diamond repository and compile it from source. I just added an option `--no-unlink`, please try using this.

**Comment by indren** [comment]
I have followed your instructions and have started a new run with the added option --no-unlink. It is still running. However, I've noticed that the log file looks different than previously. I'm including a cut version of an old run log (ran before I raised the issue) and the new run log (ran after re-installing Diamond and using --no-unlink). Is this usual?
[old_run_log.txt](https://github.com/bbuchfink/diamond/files/2864109/old_run_log.txt)
[new_run_log.txt](https://github.com/bbuchfink/diamond/files/2864111/new_run_log.txt)

**Comment by bbuchfink** [comment]
This is nothing to worry about, you are just seeing a more verbose output due to using `--log`.

**Comment by indren** [comment]
The new run got killed. The log did not specify this and just ended in:
_Processing query chunk 1, reference chunk 0, shape 0, index chunk 0.
Building reference index... Computing limits...  [0.017724s]
Building seed list...  [19.7093s]
Sorting seed list...  [11.112s]
 [30.9514s]
Building query index... Computing limits...  [0.020141s]
Building seed list..._ 

 But I realised that the log was not being updated so checked the server and found out that the run was killed:
_[8026404.974443] Out of memory: Kill process 597 (diamond) score 976 or sacrifice child
[8026404.974911] Killed process 597 (diamond) total-vm:19426116kB, anon-rss:7892068kB, file-rss:1300kB_

Any suggestions?

**Comment by bbuchfink** [comment]
You can try to use a lower block size like `-b0.5`.

**Comment by indren** [comment]
I tried -b0.5 but the run got killed due to running out of memory as previously. I can't understand why the out of memory error occurs because with -b 1.0 or lower I limit diamonds memory usage to fit my server.

**Comment by bbuchfink** [comment]
I don't know why this error occurs for you, it should be possible to run Diamond like that. I will have to investigate by trying to reproduce this problem, please be patient until then or try to find a machine with more memory.

**Comment by indren** [comment]
Thank for looking into this problem. I also have an update regarding my runs, basically I got an increase of RAM to 16G and the core count to 4. After receiving this increase I started a new diamond run with -b1.0 and --no-unlink parameters, however this run got killed. IT told me that looking at the logs there was no indication of out-of-memory termination and the SAR data showed that there was still free RAM left.

Diamonds run log showed the following error:
_Joining output blocks... Error: Format error: Invalid varint encoding.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Format error: Invalid varint encoding._

**Comment by bbuchfink** [comment]
This error would indicate that a temp file of Diamond was corrupted somehow. Can you try to start the run again and see if this error occurs again in the same spot?

**Comment by indren** [comment]
I did the re-run and it failed. However, the error I got was 'Out of memory'  and not anything to do with the temp file. I asked IT to check SAR output regarding this run and this is their response:

_SAR provides a "point in time" view of the state of the OS at regular intervals (currently set up to be every 10 minutes), so all I can add to the situation is that, yes it looks very much like you ran out of memory at about 17:15. The system had been under heavy load since about 07:30 that morning and had slowly increased RAM use throughout the day to the point where it had consumed it all (and all the swap space) by late afternoon._

This is weird, because I did get an upgrade for my server to 16G and for this run I set -b1.0. So I am not sure how or why the memory exhaustion keeps on occurring.

**Comment by bbuchfink** [comment]
I'm doing a test run now to see if I can reproduce this problem.

**Comment by bbuchfink** [comment]
I did a run with `-b1.2` and it used 21 GB of memory, which is indeed much more than it should. I will have to investigate how this happens and get back to you.

**Comment by bbuchfink** [comment]
I have found a memory leak which should now be fixed. Please try again with the latest commit.

**Comment by indren** [comment]
Thank you for looking into this! Before trying again do I need to re-install DIAMOND?

**Comment by bbuchfink** [comment]
You need to clone the repository (or use git pull if you have cloned it already) and then compile from source.

**Comment by arthurvinx** [comment]
Hi @bbuchfink, I tried to compile the latest version from the repository and I noticed some files are missing:

```
g++: error: src/util/tinythread.cpp: No such file or directory
g++: error: src/extra/roc.cpp: No such file or directory
g++: error: src/extra/model_sim.cpp: No such file or directory
g++: error: src/extra/opt.cpp: No such file or directory
```

I got them from the latest release archive, but I'm still getting errors trying to compile using `make install` or `build_simple.sh`.

Some errors from `build_simple.sh`:

```
src/util/sequence/../io/consumer.h:7:10: error:   overriding ‘virtual Consumer::~Consumer() throw ()’
  virtual ~Consumer() = default;
          ^
src/util/sequence/sequence.cpp: In function ‘void Util::Sequence::format(sequence, const char*, const char*, OutputFile&, const string&, const Value_traits&)’:
src/util/sequence/sequence.cpp:29:2: error: ‘constexpr’ was not declared in this scope
  constexpr size_t WRAP = 160;
  ^
src/util/sequence/sequence.cpp:29:12: error: expected ‘;’ before ‘size_t’
  constexpr size_t WRAP = 160;
            ^
src/util/sequence/sequence.cpp:33:45: error: ‘WRAP’ was not declared in this scope
   for (size_t i = 0; i < seq.length(); i += WRAP) {

/opt/npad/shared/compilers/gnu/7.3/include/c++/7.3.0/bits/move.h:48:37: error: ‘__builtin_addressof’ was not declared in this scope
```

Some errors from `make install`:

```
In file included from /scratch/global/dadamorais/TARA/diamond/src/basic/../data/sorted_list.h:27:0,
                 from /scratch/global/dadamorais/TARA/diamond/src/basic/config.cpp:31:
/scratch/global/dadamorais/TARA/diamond/src/basic/../data/../util/algo/hash_join.h: In function ‘void table_join(const Relation<_t>&, const Relation<_t>&, unsigned int, unsigned int, JoinResult<_t>&)’:
/scratch/global/dadamorais/TARA/diamond/src/basic/../data/../util/algo/hash_join.h:114:27: error: there are no arguments to ‘calloc’ that depend on a template parameter, so a declaration of ‘calloc’ must be available [-fpermissive]
  RelPtr *table = (RelPtr*)calloc(keys, sizeof(RelPtr));
                           ^~~~~~
/scratch/global/dadamorais/TARA/diamond/src/basic/../data/../util/algo/hash_join.h:163:2: error: there are no arguments to ‘free’ that depend on a template parameter, so a declaration of ‘free’ must be available [-fpermissive]
  free(table);
  ^~~~
make[2]: *** [CMakeFiles/diamond.dir/src/basic/config.cpp.o] Error 1
make[1]: *** [CMakeFiles/diamond.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by bbuchfink** [comment]
I tried to fix these errors, please try to clone the latest version of the repository and see if that works.

**Comment by arthurvinx** [comment]
Hello again @bbuchfink, it was successfully compiled using the `build_simple.sh` script.

The `make install` returned:

```
Scanning dependencies of target diamond
[  1%] Building CXX object CMakeFiles/diamond.dir/src/run/main.cpp.o
[  2%] Building CXX object CMakeFiles/diamond.dir/src/basic/config.cpp.o
/tmp/cc7W5uaW.s: Assembler messages:
/tmp/cc7W5uaW.s:11315: Error: no such instruction: `shlx %rax,%rdx,%rdx'
/tmp/cc7W5uaW.s:12600: Error: no such instruction: `shlx %rax,%rdx,%rdx'
make[2]: *** [CMakeFiles/diamond.dir/src/basic/config.cpp.o] Error 1
make[1]: *** [CMakeFiles/diamond.dir/all] Error 2
make: *** [all] Error 2
```

Thank you very much, you are an awesome dev..

**Comment by indren** [comment]
> You need to clone the repository (or use git pull if you have cloned it already) and then compile from source.

I have completed a DIAMOND run. Thank you for your help!
